### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NotJuniorFoxy** [officialrealTM/mcserver_installer#5]
./start.sh: 1: function: not found
grep: javaversion.txt: No such file or directory
grep: javaversion.txt: No such file or directory
grep: javaversion.txt: No such file or directory
rm: cannot remove 'javaversion.txt': No such file or directory
./start.sh: 19: Syntax error: "}" unexpected

**Comment by officialrealTM** [comment]
@NotJuniorFoxy I need more details such as:
- On what Linux Distro you've executed it
- Have you installed it correctly.

To further investigate, please consider joining my [Discord](https://realtm.link/discord)

**Comment by officialrealTM** [comment]
Unfortunately you didn't answer. --> Closing issue
