### ISSUE TITLE
When i run the "start.sh" it shows [screen is terminating]

### ISSUE THREAD

**Issue by Nikilites** [officialrealTM/mcserver_installer#7]
![immagine](https://github.com/officialrealTM/mcserver_installer/assets/109990495/8e87c2fa-ecdd-48d9-affe-67355f4684b7)

**Comment by officialrealTM** [comment]
Hey @Nikilites ,
I tried to reproduce this error with Forge 1.20.2 Build 14.23.5.2859.
I didn't get an error.

Would you mind joining my [Discord](https://realtm.link/discord) so we can look through it together?

**Comment by Nikilites** [comment]
If it helps, I'm running it in a docker container.

**Comment by officialrealTM** [comment]
@Nikilites 
I haven't tested it in a docker container yet - As I said: It would be cool if you would join my Discord server so we can investigate together.

**Comment by officialrealTM** [comment]
Issue found -> Script not working inside of docker containers due to it using absolute paths
