### ISSUE TITLE
Add support for Quilt

### ISSUE THREAD

**Issue by Darx699** [officialrealTM/mcserver_installer#8]
Hey! I love the script but could you possibly make it compatible with Quilt?

**Comment by officialrealTM** [comment]
Hey, thanks for the feedback!
I thought a few days about your request but need to decline it for now.
I actually never heard of Quilt and took the time to have a look at it.
Seems like a nice project!
Unfortunately the API they provide is still in v1 and not that advanced yet! I want to avoid hard-coding everything in, so being able to obtain the different builds/version for each major version would be greate but not possible yet.
Moreover, Quilt also provides versions that can be ran on snapshot version of Minecraft which my script does not support.

But I keep it in the back of my mind and may add it at a later point!

In the meantime: You are happy to program this in yourself and then create a PR - Then I can have a look and if I'm happy merge it into my script!

Thanks for the feedback though!
Have a nice day.

/TM
